name: Publish Package
description: 'Publish the package to PyPI'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ inputs.dry_run == 'false' }}
      with:
        password: ${{inputs.token}}
