name: Publish Package
description: 'Publish the package to PyPI'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
        pip install wheel
        pip install setuptools

    - name: Building publishable packages
      shell: bash
      run: python setup.py sdist bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ inputs.dry_run == 'false' }}
      with:
        password: ${{inputs.token}}
